/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as ThreatIntelRouteImport } from './routes/threat-intel'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SpectrumRouteImport } from './routes/spectrum'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as SensorsRouteImport } from './routes/sensors'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlaybooksRouteImport } from './routes/playbooks'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveFeedRouteImport } from './routes/live-feed'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as GeoZonesRouteImport } from './routes/geo-zones'
import { Route as CommandRouteImport } from './routes/command'
import { Route as CamerasRouteImport } from './routes/cameras'
import { Route as CalibrationRouteImport } from './routes/calibration'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiControlRouteImport } from './routes/ai-control'
import { Route as IndexRouteImport } from './routes/index'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatIntelRoute = ThreatIntelRouteImport.update({
  id: '/threat-intel',
  path: '/threat-intel',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectrumRoute = SpectrumRouteImport.update({
  id: '/spectrum',
  path: '/spectrum',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsRoute = SensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksRoute = PlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveFeedRoute = LiveFeedRouteImport.update({
  id: '/live-feed',
  path: '/live-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoZonesRoute = GeoZonesRouteImport.update({
  id: '/geo-zones',
  path: '/geo-zones',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerasRoute = CamerasRouteImport.update({
  id: '/cameras',
  path: '/cameras',
  getParentRoute: () => rootRouteImport,
} as any)
const CalibrationRoute = CalibrationRouteImport.update({
  id: '/calibration',
  path: '/calibration',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiControlRoute = AiControlRouteImport.update({
  id: '/ai-control',
  path: '/ai-control',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-control': typeof AiControlRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/calibration': typeof CalibrationRoute
  '/cameras': typeof CamerasRoute
  '/command': typeof CommandRoute
  '/geo-zones': typeof GeoZonesRoute
  '/incidents': typeof IncidentsRoute
  '/integrations': typeof IntegrationsRoute
  '/live-feed': typeof LiveFeedRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/notifications': typeof NotificationsRoute
  '/playbooks': typeof PlaybooksRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/sensors': typeof SensorsRoute
  '/simulation': typeof SimulationRoute
  '/spectrum': typeof SpectrumRoute
  '/team': typeof TeamRoute
  '/threat-intel': typeof ThreatIntelRoute
  '/weather': typeof WeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-control': typeof AiControlRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/calibration': typeof CalibrationRoute
  '/cameras': typeof CamerasRoute
  '/command': typeof CommandRoute
  '/geo-zones': typeof GeoZonesRoute
  '/incidents': typeof IncidentsRoute
  '/integrations': typeof IntegrationsRoute
  '/live-feed': typeof LiveFeedRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/notifications': typeof NotificationsRoute
  '/playbooks': typeof PlaybooksRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/sensors': typeof SensorsRoute
  '/simulation': typeof SimulationRoute
  '/spectrum': typeof SpectrumRoute
  '/team': typeof TeamRoute
  '/threat-intel': typeof ThreatIntelRoute
  '/weather': typeof WeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-control': typeof AiControlRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/calibration': typeof CalibrationRoute
  '/cameras': typeof CamerasRoute
  '/command': typeof CommandRoute
  '/geo-zones': typeof GeoZonesRoute
  '/incidents': typeof IncidentsRoute
  '/integrations': typeof IntegrationsRoute
  '/live-feed': typeof LiveFeedRoute
  '/login': typeof LoginRoute
  '/missions': typeof MissionsRoute
  '/notifications': typeof NotificationsRoute
  '/playbooks': typeof PlaybooksRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/sensors': typeof SensorsRoute
  '/simulation': typeof SimulationRoute
  '/spectrum': typeof SpectrumRoute
  '/team': typeof TeamRoute
  '/threat-intel': typeof ThreatIntelRoute
  '/weather': typeof WeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-control'
    | '/analytics'
    | '/audit'
    | '/calibration'
    | '/cameras'
    | '/command'
    | '/geo-zones'
    | '/incidents'
    | '/integrations'
    | '/live-feed'
    | '/login'
    | '/missions'
    | '/notifications'
    | '/playbooks'
    | '/profile'
    | '/reports'
    | '/sensors'
    | '/simulation'
    | '/spectrum'
    | '/team'
    | '/threat-intel'
    | '/weather'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-control'
    | '/analytics'
    | '/audit'
    | '/calibration'
    | '/cameras'
    | '/command'
    | '/geo-zones'
    | '/incidents'
    | '/integrations'
    | '/live-feed'
    | '/login'
    | '/missions'
    | '/notifications'
    | '/playbooks'
    | '/profile'
    | '/reports'
    | '/sensors'
    | '/simulation'
    | '/spectrum'
    | '/team'
    | '/threat-intel'
    | '/weather'
  id:
    | '__root__'
    | '/'
    | '/ai-control'
    | '/analytics'
    | '/audit'
    | '/calibration'
    | '/cameras'
    | '/command'
    | '/geo-zones'
    | '/incidents'
    | '/integrations'
    | '/live-feed'
    | '/login'
    | '/missions'
    | '/notifications'
    | '/playbooks'
    | '/profile'
    | '/reports'
    | '/sensors'
    | '/simulation'
    | '/spectrum'
    | '/team'
    | '/threat-intel'
    | '/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiControlRoute: typeof AiControlRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditRoute: typeof AuditRoute
  CalibrationRoute: typeof CalibrationRoute
  CamerasRoute: typeof CamerasRoute
  CommandRoute: typeof CommandRoute
  GeoZonesRoute: typeof GeoZonesRoute
  IncidentsRoute: typeof IncidentsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LiveFeedRoute: typeof LiveFeedRoute
  LoginRoute: typeof LoginRoute
  MissionsRoute: typeof MissionsRoute
  NotificationsRoute: typeof NotificationsRoute
  PlaybooksRoute: typeof PlaybooksRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  SensorsRoute: typeof SensorsRoute
  SimulationRoute: typeof SimulationRoute
  SpectrumRoute: typeof SpectrumRoute
  TeamRoute: typeof TeamRoute
  ThreatIntelRoute: typeof ThreatIntelRoute
  WeatherRoute: typeof WeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-intel': {
      id: '/threat-intel'
      path: '/threat-intel'
      fullPath: '/threat-intel'
      preLoaderRoute: typeof ThreatIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectrum': {
      id: '/spectrum'
      path: '/spectrum'
      fullPath: '/spectrum'
      preLoaderRoute: typeof SpectrumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors': {
      id: '/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof SensorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks': {
      id: '/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof PlaybooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-feed': {
      id: '/live-feed'
      path: '/live-feed'
      fullPath: '/live-feed'
      preLoaderRoute: typeof LiveFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo-zones': {
      id: '/geo-zones'
      path: '/geo-zones'
      fullPath: '/geo-zones'
      preLoaderRoute: typeof GeoZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameras': {
      id: '/cameras'
      path: '/cameras'
      fullPath: '/cameras'
      preLoaderRoute: typeof CamerasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calibration': {
      id: '/calibration'
      path: '/calibration'
      fullPath: '/calibration'
      preLoaderRoute: typeof CalibrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-control': {
      id: '/ai-control'
      path: '/ai-control'
      fullPath: '/ai-control'
      preLoaderRoute: typeof AiControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiControlRoute: AiControlRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditRoute: AuditRoute,
  CalibrationRoute: CalibrationRoute,
  CamerasRoute: CamerasRoute,
  CommandRoute: CommandRoute,
  GeoZonesRoute: GeoZonesRoute,
  IncidentsRoute: IncidentsRoute,
  IntegrationsRoute: IntegrationsRoute,
  LiveFeedRoute: LiveFeedRoute,
  LoginRoute: LoginRoute,
  MissionsRoute: MissionsRoute,
  NotificationsRoute: NotificationsRoute,
  PlaybooksRoute: PlaybooksRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  SensorsRoute: SensorsRoute,
  SimulationRoute: SimulationRoute,
  SpectrumRoute: SpectrumRoute,
  TeamRoute: TeamRoute,
  ThreatIntelRoute: ThreatIntelRoute,
  WeatherRoute: WeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
